const symptomsKeywords = [
    "fever", "chills", "sweats", "cough", "dry cough", "wet cough", "headache", "migraine",
    "sore throat", "scratchy throat", "runny nose", "stuffy nose", "nasal congestion", "sneezing",
    "shortness of breath", "difficulty breathing", "wheezing", "chest pain", "chest tightness",
    "rapid heartbeat", "palpitations", "fatigue", "weakness", "tiredness", "dizziness",
    "lightheadedness", "fainting", "nausea", "vomiting", "upset stomach", "stomach pain",
    "abdominal pain", "diarrhea", "constipation", "bloating", "gas", "indigestion", "heartburn",
    "loss of appetite", "weight loss", "weight gain", "muscle pain", "muscle cramps", "joint pain",
    "stiff joints", "swollen joints", "back pain", "neck pain", "shoulder pain", "knee pain",
    "ankle pain", "hip pain", "wrist pain", "hand pain", "foot pain", "leg pain", "arm pain",
    "finger pain", "toe pain", "skin rash", "itchy skin", "hives", "blisters", "bruises",
    "swelling", "redness", "warmth", "painful urination", "frequent urination", "urgent urination",
    "urinary incontinence", "blood in urine", "cloudy urine", "dark urine", "ear pain", "earache",
    "hearing loss", "ringing in ears", "ear discharge", "itchy ears", "sore eyes", "red eyes",
    "itchy eyes", "watery eyes", "blurred vision", "double vision", "eye pain", "sensitivity to light",
    "dry eyes", "eye discharge", "mouth sores", "mouth ulcers", "gum pain", "toothache", "bad breath",
    "dry mouth", "difficulty swallowing", "hoarseness", "voice changes", "swollen lymph nodes", "lumps",
    "bumps", "night sweats", "shaking", "tremors", "seizures", "memory loss", "confusion",
    "difficulty concentrating", "mood swings", "irritability", "anxiety", "depression", "panic attacks",
    "hallucinations", "delusions", "paranoia", "insomnia", "sleep disturbances", "nightmares", "snoring",
    "excessive sleepiness", "itchy scalp", "hair loss", "brittle nails", "yellow nails", "bleeding gums",
    "nosebleeds", "bleeding", "easy bruising", "anemia", "jaundice", "yellow skin", "yellow eyes",
    "pale skin", "cyanosis", "blue lips", "blue fingertips", "tingling", "numbness", "burning sensation",
    "prickling sensation", "cold hands", "cold feet", "hot flashes", "excessive sweating", "decreased sweating",
    "dry skin", "scaly skin", "peeling skin", "cracked skin", "thickened skin", "skin discoloration",
    "ulcers", "sores", "slow wound healing", "chronic pain", "acute pain", "intermittent pain", "constant pain",
    "sharp pain", "dull pain", "aching", "burning pain", "throbbing pain", "stabbing pain", "pressure",
    "tightness", "heaviness", "shooting pain", "radiating pain", "localized pain", "generalized pain",
    "tenderness", "soreness", "fatigue", "malaise", "lethargy", "weakness", "lack of energy", "muscle weakness",
    "joint stiffness", "muscle stiffness", "difficulty moving", "limited range of motion", "spasticity",
    "muscle twitching", "muscle jerking", "cramps", "spasms", "paralysis", "loss of sensation",
    "loss of coordination", "balance problems", "difficulty walking", "gait changes", "posture changes",
    "trembling", "shaking hands", "shaky legs", "clumsiness", "poor coordination", "dizziness", "vertigo",
    "lightheadedness", "spinning sensation", "unsteadiness", "feeling faint", "blackouts", "syncope",
    "loss of consciousness", "memory problems", "forgetfulness", "amnesia", "confusion", "disorientation",
    "difficulty concentrating", "inattention", "distractibility", "slow thinking", "delayed response",
    "word-finding difficulty", "difficulty speaking", "slurred speech", "mumbling", "difficulty understanding",
    "difficulty writing", "difficulty reading", "difficulty learning", "mental fog", "brain fog", "poor judgment",
    "impulsivity", "racing thoughts", "irrational thoughts", "obsessive thoughts", "compulsive behaviors",
    "repetitive behaviors", "phobias", "fears", "excessive worrying", "excessive fear", "unrealistic fears",
    "panic attacks", "anxiety attacks", "social anxiety", "agoraphobia", "claustrophobia", "fear of heights",
    "fear of flying", "fear of germs", "fear of illness", "fear of death", "depression", "sadness", "hopelessness",
    "helplessness", "worthlessness", "guilt", "shame", "low self-esteem", "loss of interest", "loss of pleasure",
    "withdrawal", "isolation", "crying spells", "tearfulness", "anger", "irritability", "frustration", "restlessness",
    "agitation", "fatigue", "excessive sleeping", "insomnia", "early morning waking", "middle of the night waking",
    "difficulty falling asleep", "poor sleep quality", "nightmares", "vivid dreams", "daytime sleepiness", "tiredness",
    "fatigue", "low energy", "lack of motivation", "difficulty making decisions", "indecisiveness", "procrastination",
    "difficulty starting tasks", "difficulty completing tasks", "slowed thinking", "slowed movements", "thoughts of death",
    "thoughts of suicide", "self-harm", "cutting", "burning", "scratching", "hitting", "banging head", "biting",
    "pulling hair", "eating problems", "overeating", "undereating", "binge eating", "purging", "restricting food",
    "body image issues", "weight changes", "muscle pain", "joint pain", "back pain", "neck pain", "headaches",
    "migraines", "abdominal pain", "chest pain", "palpitations", "shortness of breath", "difficulty breathing", "wheezing",
    "coughing", "choking", "gagging", "nausea", "vomiting", "diarrhea", "constipation", "bloating", "gas", "indigestion",
    "heartburn", "loss of appetite", "weight loss", "weight gain", "frequent urination", "painful urination", "blood in urine",
    "cloudy urine", "dark urine", "vaginal discharge", "vaginal itching", "vaginal dryness", "painful intercourse",
    "irregular periods", "missed periods", "heavy periods", "light periods", "spotting", "menstrual cramps", "PMS", "breast pain"
    // Add more keywords as needed
  ];
  
  export default symptomsKeywords;
  